# Ruby gem file with fastlane dependencies.
# cf. https://docs.fastlane.tools/getting-started/ios/setup/
source "https://rubygems.org"

gem "fastlane"


plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
