stages:
    - build
    - test


build:android:
    stage: build
    when: manual
    allow_failure: false
    tags:
        - docker
    image: registry.gitlab.com/pnplab/flux/android-builder:latest
    variables:
        GRADLE_OUTPUT_PATH: android/app/build/outputs/apk/release/app-universal-release.apk
        OUTPUT_APK: ${CI_PROJECT_NAME}.${CI_COMMIT_REF_SLUG}.${CI_COMMIT_SHORT_SHA}.apk
    artifacts:
        name: ${OUTPUT_APK}
        paths:
            - ${OUTPUT_APK}
        expire_in: 7 days
    cache:
        key: build.${CI_PROJECT_ID}
        paths:
            - android/.gradle/
            - node_modules/
    before_script:
        - yarn
    script:
        # Those variables have to be set in gitlab ci/cd environment variables
        # @note we need to add `-e` to expand `\n` into new lines in gitlab! 
        - echo -e "FLUX_RELEASE_STORE_FILE=flux-release-key.keystore\nFLUX_RELEASE_KEY_ALIAS=${FLUX_RELEASE_KEY_ALIAS}\nFLUX_RELEASE_STORE_PASSWORD=${FLUX_RELEASE_STORE_PASSWORD}\nFLUX_RELEASE_KEY_PASSWORD=${FLUX_RELEASE_KEY_PASSWORD}" > android/gradle.properties
        # Generated through `base64 -i android/app/flux-release-key.keystore -o <outfile>`
        - echo ${FLUX_RELEASE_KEY_KEYSTORE_B64} | base64 -d > android/app/flux-release-key.keystore
        - echo ${GOOGLE_SERVICES_JSON} > android/app/google-services.json
        - cd android && ./gradlew assembleRelease -PFLUX_RELEASE_STORE_PASSWORD=${FLUX_RELEASE_STORE_PASSWORD} -PFLUX_RELEASE_KEY_PASSWORD=${FLUX_RELEASE_KEY_PASSWORD} && cd ..
    after_script:
        - cp ${GRADLE_OUTPUT_PATH} ${OUTPUT_APK}


test:android:
    stage: test
    dependencies:
        - build:android
    # when: manual
    variables:
        APK_FILE: ${CI_PROJECT_NAME}.${CI_COMMIT_REF_SLUG}.${CI_COMMIT_SHORT_SHA}.apk
    tags:
        - docker
    image: registry.gitlab.com/pnplab/flux/test-farm-runner:latest
    script:
        - aws configure set default.region ${AWS_REGION}
        - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
        - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
        - ./scripts/tests/package_tests.sh && ./scripts/tests/upload_tests.sh &
        - ./scripts/tests/upload_yaml.sh &
        - ./scripts/tests/upload_app.sh "${APK_FILE}" &
        - wait
        - export RUN_ARN=$(./scripts/tests/run.sh -q)
        - ./scripts/tests/poll_run_results.sh -a ${RUN_ARN} -q

# build:ios:
#     variables:
#         PLATFORM: ios
#         FILE_TYPE: ipa
#         OUTPUT_PATH: ./$CI_PROJECT_NAME
#     <<: *job_build
#     script:
#         - export PACKAGE_NAME=$(node -p -e "require('./package.json').name")
#         - cd ios
#         - xcodebuild -scheme $PACKAGE_NAME archive -archivePath $PACKAGE_NAME.xcarchive -allowProvisioningUpdates
#         - xcodebuild -exportArchive -archivePath ./$PACKAGE_NAME.xcarchive -exportPath . -exportOptionsPlist $PACKAGE_NAME/Info.plist
#         - mv $PACKAGE_NAME.ipa ../$PACKAGE_NAME.ipa
